### ISSUE TITLE
Challenge 1

### ISSUE THREAD

**Issue by MKhodagholi** [theMohmd/Ava#1]
با سلام و عرض خسته نباشید

چند نکته درباره طرح پیاده سازی شده:
۱. در جاهایی که المنت نیاز نیست اسکرول شود نباید اسکرول بار نمایش داده بشود.
۲. در صفحه آرشیو تایتل های جدول شبیه طراحی نیست.
۳. در صفحه آرشیو آیتم های جدول شبیه طراحی نیستند. (سایه ندارند)
۴. در خیلی از جاها اندازه فونت نوشته ها شبیه طراحی نیستند.
۵. ساید بارمنو راست شبیه طراحی پیاده سازی نشده است.

**Comment by theMohmd** [comment]
با سلام
-مشکل اسکرول بار در فایرفاکس وجود نداشت و  پس از متوجه شدن درکامیت های بعدی اصلاح شده ولی در برنچ ch2-3 این اصلاحات صورت گرفته.
- تایتل ها اصلاح شدند.
-آیتم های جدول سایه داشتند ولی بجای یک در میان بودن سایه همه آنها سایه داشتند که اصلاح شد.
-اندازه فونت ها مطابق طراحی میباشد ولی بدلیل نداشتن تمامی font weight ها نمایش داده نمی‌شوند.
-متوجه منظورتان از تشابه نشدم لطفا بیشتر توضیح دهید.

**Comment by theMohmd** [comment]
با سلام

مشکل اسکرول بار در فایرفاکس وجود نداشت و پس از متوجه شدن درکامیت های بعدی اصلاح شده ولی در برنچ ch2-3 این اصلاحات صورت گرفته.

تایتل ها اصلاح شدند.

آیتم های جدول سایه داشتند ولی بجای یک در میان بودن سایه همه آنها سایه داشتند که اصلاح شد.

اندازه فونت ها مطابق طراحی میباشد ولی بدلیل نداشتن تمامی font weight ها نمایش داده نمی‌شوند.

متوجه منظورتان از تشابه نشدم لطفا بیشتر توضیح دهید.

**Comment by MKhodagholi** [comment]
خیلی ممنون بابت اصلاحات جدید؛
آیتم ها وقتی hover می‌شوند سایه میگیرند و در حالت عادی هیچ یک از آیتم ها سایه ندارند.
اندازه فونت ها یعنی font-size، اونی که شما میگید font-weight هست و خب مثلا در طراحی در صفحه آرشیو، نام هر یک از فایل 16px s هست ولی در پیاده سازی شما 20px هست.
منو سمت راست اگه دقت کنید لینک هر صفحه آیکونش در یک راستا هست ولی برای پیاده سازی شما این چنین نیست.

**Comment by theMohmd** [comment]
تمامی نکات اصلاح شدند.

**Comment by MKhodagholi** [comment]
تشکر
